// Países + código de discagem (DDI/E.164). A bandeira é derivada do ISO-2
// (regional indicators), então guardamos só {ddi, iso, nome} — menos erro.
export type Pais = { ddi: string; iso: string; nome: string };

const RAW: Pais[] = [
  { ddi: "55", iso: "BR", nome: "Brasil" },
  { ddi: "93", iso: "AF", nome: "Afeganistão" },
  { ddi: "27", iso: "ZA", nome: "África do Sul" },
  { ddi: "355", iso: "AL", nome: "Albânia" },
  { ddi: "49", iso: "DE", nome: "Alemanha" },
  { ddi: "376", iso: "AD", nome: "Andorra" },
  { ddi: "244", iso: "AO", nome: "Angola" },
  { ddi: "1264", iso: "AI", nome: "Anguila" },
  { ddi: "1268", iso: "AG", nome: "Antígua e Barbuda" },
  { ddi: "966", iso: "SA", nome: "Arábia Saudita" },
  { ddi: "213", iso: "DZ", nome: "Argélia" },
  { ddi: "54", iso: "AR", nome: "Argentina" },
  { ddi: "374", iso: "AM", nome: "Armênia" },
  { ddi: "297", iso: "AW", nome: "Aruba" },
  { ddi: "61", iso: "AU", nome: "Austrália" },
  { ddi: "43", iso: "AT", nome: "Áustria" },
  { ddi: "994", iso: "AZ", nome: "Azerbaijão" },
  { ddi: "1242", iso: "BS", nome: "Bahamas" },
  { ddi: "973", iso: "BH", nome: "Bahrein" },
  { ddi: "880", iso: "BD", nome: "Bangladesh" },
  { ddi: "1246", iso: "BB", nome: "Barbados" },
  { ddi: "32", iso: "BE", nome: "Bélgica" },
  { ddi: "501", iso: "BZ", nome: "Belize" },
  { ddi: "229", iso: "BJ", nome: "Benin" },
  { ddi: "1441", iso: "BM", nome: "Bermudas" },
  { ddi: "375", iso: "BY", nome: "Bielorrússia" },
  { ddi: "591", iso: "BO", nome: "Bolívia" },
  { ddi: "387", iso: "BA", nome: "Bósnia e Herzegovina" },
  { ddi: "267", iso: "BW", nome: "Botsuana" },
  { ddi: "673", iso: "BN", nome: "Brunei" },
  { ddi: "359", iso: "BG", nome: "Bulgária" },
  { ddi: "226", iso: "BF", nome: "Burkina Faso" },
  { ddi: "257", iso: "BI", nome: "Burundi" },
  { ddi: "975", iso: "BT", nome: "Butão" },
  { ddi: "238", iso: "CV", nome: "Cabo Verde" },
  { ddi: "237", iso: "CM", nome: "Camarões" },
  { ddi: "855", iso: "KH", nome: "Camboja" },
  { ddi: "1", iso: "CA", nome: "Canadá" },
  { ddi: "974", iso: "QA", nome: "Catar" },
  { ddi: "7", iso: "KZ", nome: "Cazaquistão" },
  { ddi: "235", iso: "TD", nome: "Chade" },
  { ddi: "56", iso: "CL", nome: "Chile" },
  { ddi: "86", iso: "CN", nome: "China" },
  { ddi: "357", iso: "CY", nome: "Chipre" },
  { ddi: "65", iso: "SG", nome: "Cingapura" },
  { ddi: "57", iso: "CO", nome: "Colômbia" },
  { ddi: "269", iso: "KM", nome: "Comores" },
  { ddi: "242", iso: "CG", nome: "Congo" },
  { ddi: "243", iso: "CD", nome: "Congo (RDC)" },
  { ddi: "850", iso: "KP", nome: "Coreia do Norte" },
  { ddi: "82", iso: "KR", nome: "Coreia do Sul" },
  { ddi: "225", iso: "CI", nome: "Costa do Marfim" },
  { ddi: "506", iso: "CR", nome: "Costa Rica" },
  { ddi: "385", iso: "HR", nome: "Croácia" },
  { ddi: "53", iso: "CU", nome: "Cuba" },
  { ddi: "599", iso: "CW", nome: "Curaçao" },
  { ddi: "45", iso: "DK", nome: "Dinamarca" },
  { ddi: "253", iso: "DJ", nome: "Djibuti" },
  { ddi: "1767", iso: "DM", nome: "Dominica" },
  { ddi: "20", iso: "EG", nome: "Egito" },
  { ddi: "503", iso: "SV", nome: "El Salvador" },
  { ddi: "971", iso: "AE", nome: "Emirados Árabes Unidos" },
  { ddi: "593", iso: "EC", nome: "Equador" },
  { ddi: "291", iso: "ER", nome: "Eritreia" },
  { ddi: "421", iso: "SK", nome: "Eslováquia" },
  { ddi: "386", iso: "SI", nome: "Eslovênia" },
  { ddi: "34", iso: "ES", nome: "Espanha" },
  { ddi: "1", iso: "US", nome: "Estados Unidos" },
  { ddi: "372", iso: "EE", nome: "Estônia" },
  { ddi: "268", iso: "SZ", nome: "Essuatíni" },
  { ddi: "251", iso: "ET", nome: "Etiópia" },
  { ddi: "679", iso: "FJ", nome: "Fiji" },
  { ddi: "63", iso: "PH", nome: "Filipinas" },
  { ddi: "358", iso: "FI", nome: "Finlândia" },
  { ddi: "33", iso: "FR", nome: "França" },
  { ddi: "241", iso: "GA", nome: "Gabão" },
  { ddi: "220", iso: "GM", nome: "Gâmbia" },
  { ddi: "233", iso: "GH", nome: "Gana" },
  { ddi: "995", iso: "GE", nome: "Geórgia" },
  { ddi: "1473", iso: "GD", nome: "Granada" },
  { ddi: "30", iso: "GR", nome: "Grécia" },
  { ddi: "299", iso: "GL", nome: "Groenlândia" },
  { ddi: "590", iso: "GP", nome: "Guadalupe" },
  { ddi: "1671", iso: "GU", nome: "Guam" },
  { ddi: "502", iso: "GT", nome: "Guatemala" },
  { ddi: "592", iso: "GY", nome: "Guiana" },
  { ddi: "594", iso: "GF", nome: "Guiana Francesa" },
  { ddi: "224", iso: "GN", nome: "Guiné" },
  { ddi: "240", iso: "GQ", nome: "Guiné Equatorial" },
  { ddi: "245", iso: "GW", nome: "Guiné-Bissau" },
  { ddi: "509", iso: "HT", nome: "Haiti" },
  { ddi: "504", iso: "HN", nome: "Honduras" },
  { ddi: "852", iso: "HK", nome: "Hong Kong" },
  { ddi: "36", iso: "HU", nome: "Hungria" },
  { ddi: "967", iso: "YE", nome: "Iêmen" },
  { ddi: "1345", iso: "KY", nome: "Ilhas Cayman" },
  { ddi: "298", iso: "FO", nome: "Ilhas Faroé" },
  { ddi: "692", iso: "MH", nome: "Ilhas Marshall" },
  { ddi: "677", iso: "SB", nome: "Ilhas Salomão" },
  { ddi: "1284", iso: "VG", nome: "Ilhas Virgens Britânicas" },
  { ddi: "1340", iso: "VI", nome: "Ilhas Virgens Americanas" },
  { ddi: "91", iso: "IN", nome: "Índia" },
  { ddi: "62", iso: "ID", nome: "Indonésia" },
  { ddi: "98", iso: "IR", nome: "Irã" },
  { ddi: "964", iso: "IQ", nome: "Iraque" },
  { ddi: "353", iso: "IE", nome: "Irlanda" },
  { ddi: "354", iso: "IS", nome: "Islândia" },
  { ddi: "972", iso: "IL", nome: "Israel" },
  { ddi: "39", iso: "IT", nome: "Itália" },
  { ddi: "1876", iso: "JM", nome: "Jamaica" },
  { ddi: "81", iso: "JP", nome: "Japão" },
  { ddi: "962", iso: "JO", nome: "Jordânia" },
  { ddi: "965", iso: "KW", nome: "Kuwait" },
  { ddi: "856", iso: "LA", nome: "Laos" },
  { ddi: "266", iso: "LS", nome: "Lesoto" },
  { ddi: "371", iso: "LV", nome: "Letônia" },
  { ddi: "961", iso: "LB", nome: "Líbano" },
  { ddi: "231", iso: "LR", nome: "Libéria" },
  { ddi: "218", iso: "LY", nome: "Líbia" },
  { ddi: "423", iso: "LI", nome: "Liechtenstein" },
  { ddi: "370", iso: "LT", nome: "Lituânia" },
  { ddi: "352", iso: "LU", nome: "Luxemburgo" },
  { ddi: "853", iso: "MO", nome: "Macau" },
  { ddi: "389", iso: "MK", nome: "Macedônia do Norte" },
  { ddi: "261", iso: "MG", nome: "Madagascar" },
  { ddi: "60", iso: "MY", nome: "Malásia" },
  { ddi: "265", iso: "MW", nome: "Malaui" },
  { ddi: "960", iso: "MV", nome: "Maldivas" },
  { ddi: "223", iso: "ML", nome: "Mali" },
  { ddi: "356", iso: "MT", nome: "Malta" },
  { ddi: "212", iso: "MA", nome: "Marrocos" },
  { ddi: "596", iso: "MQ", nome: "Martinica" },
  { ddi: "222", iso: "MR", nome: "Mauritânia" },
  { ddi: "230", iso: "MU", nome: "Maurício" },
  { ddi: "52", iso: "MX", nome: "México" },
  { ddi: "95", iso: "MM", nome: "Mianmar" },
  { ddi: "691", iso: "FM", nome: "Micronésia" },
  { ddi: "258", iso: "MZ", nome: "Moçambique" },
  { ddi: "373", iso: "MD", nome: "Moldávia" },
  { ddi: "377", iso: "MC", nome: "Mônaco" },
  { ddi: "976", iso: "MN", nome: "Mongólia" },
  { ddi: "382", iso: "ME", nome: "Montenegro" },
  { ddi: "264", iso: "NA", nome: "Namíbia" },
  { ddi: "674", iso: "NR", nome: "Nauru" },
  { ddi: "977", iso: "NP", nome: "Nepal" },
  { ddi: "505", iso: "NI", nome: "Nicarágua" },
  { ddi: "227", iso: "NE", nome: "Níger" },
  { ddi: "234", iso: "NG", nome: "Nigéria" },
  { ddi: "47", iso: "NO", nome: "Noruega" },
  { ddi: "687", iso: "NC", nome: "Nova Caledônia" },
  { ddi: "64", iso: "NZ", nome: "Nova Zelândia" },
  { ddi: "968", iso: "OM", nome: "Omã" },
  { ddi: "31", iso: "NL", nome: "Países Baixos" },
  { ddi: "680", iso: "PW", nome: "Palau" },
  { ddi: "970", iso: "PS", nome: "Palestina" },
  { ddi: "507", iso: "PA", nome: "Panamá" },
  { ddi: "675", iso: "PG", nome: "Papua-Nova Guiné" },
  { ddi: "92", iso: "PK", nome: "Paquistão" },
  { ddi: "595", iso: "PY", nome: "Paraguai" },
  { ddi: "51", iso: "PE", nome: "Peru" },
  { ddi: "689", iso: "PF", nome: "Polinésia Francesa" },
  { ddi: "48", iso: "PL", nome: "Polônia" },
  { ddi: "1787", iso: "PR", nome: "Porto Rico" },
  { ddi: "351", iso: "PT", nome: "Portugal" },
  { ddi: "254", iso: "KE", nome: "Quênia" },
  { ddi: "996", iso: "KG", nome: "Quirguistão" },
  { ddi: "686", iso: "KI", nome: "Quiribati" },
  { ddi: "44", iso: "GB", nome: "Reino Unido" },
  { ddi: "236", iso: "CF", nome: "República Centro-Africana" },
  { ddi: "1809", iso: "DO", nome: "República Dominicana" },
  { ddi: "420", iso: "CZ", nome: "República Tcheca" },
  { ddi: "262", iso: "RE", nome: "Reunião" },
  { ddi: "40", iso: "RO", nome: "Romênia" },
  { ddi: "250", iso: "RW", nome: "Ruanda" },
  { ddi: "7", iso: "RU", nome: "Rússia" },
  { ddi: "685", iso: "WS", nome: "Samoa" },
  { ddi: "378", iso: "SM", nome: "San Marino" },
  { ddi: "1758", iso: "LC", nome: "Santa Lúcia" },
  { ddi: "1869", iso: "KN", nome: "São Cristóvão e Nevis" },
  { ddi: "239", iso: "ST", nome: "São Tomé e Príncipe" },
  { ddi: "1784", iso: "VC", nome: "São Vicente e Granadinas" },
  { ddi: "248", iso: "SC", nome: "Seicheles" },
  { ddi: "221", iso: "SN", nome: "Senegal" },
  { ddi: "232", iso: "SL", nome: "Serra Leoa" },
  { ddi: "381", iso: "RS", nome: "Sérvia" },
  { ddi: "963", iso: "SY", nome: "Síria" },
  { ddi: "252", iso: "SO", nome: "Somália" },
  { ddi: "94", iso: "LK", nome: "Sri Lanka" },
  { ddi: "249", iso: "SD", nome: "Sudão" },
  { ddi: "211", iso: "SS", nome: "Sudão do Sul" },
  { ddi: "46", iso: "SE", nome: "Suécia" },
  { ddi: "41", iso: "CH", nome: "Suíça" },
  { ddi: "597", iso: "SR", nome: "Suriname" },
  { ddi: "66", iso: "TH", nome: "Tailândia" },
  { ddi: "886", iso: "TW", nome: "Taiwan" },
  { ddi: "992", iso: "TJ", nome: "Tajiquistão" },
  { ddi: "255", iso: "TZ", nome: "Tanzânia" },
  { ddi: "670", iso: "TL", nome: "Timor-Leste" },
  { ddi: "228", iso: "TG", nome: "Togo" },
  { ddi: "676", iso: "TO", nome: "Tonga" },
  { ddi: "1868", iso: "TT", nome: "Trinidad e Tobago" },
  { ddi: "216", iso: "TN", nome: "Tunísia" },
  { ddi: "993", iso: "TM", nome: "Turcomenistão" },
  { ddi: "90", iso: "TR", nome: "Turquia" },
  { ddi: "688", iso: "TV", nome: "Tuvalu" },
  { ddi: "380", iso: "UA", nome: "Ucrânia" },
  { ddi: "256", iso: "UG", nome: "Uganda" },
  { ddi: "598", iso: "UY", nome: "Uruguai" },
  { ddi: "998", iso: "UZ", nome: "Uzbequistão" },
  { ddi: "678", iso: "VU", nome: "Vanuatu" },
  { ddi: "379", iso: "VA", nome: "Vaticano" },
  { ddi: "58", iso: "VE", nome: "Venezuela" },
  { ddi: "84", iso: "VN", nome: "Vietnã" },
  { ddi: "260", iso: "ZM", nome: "Zâmbia" },
  { ddi: "263", iso: "ZW", nome: "Zimbábue" },
];

// Brasil primeiro, o resto em ordem alfabética (pt-BR).
export const PAISES: Pais[] = [
  ...RAW.filter((p) => p.iso === "BR"),
  ...RAW.filter((p) => p.iso !== "BR").sort((a, b) => a.nome.localeCompare(b.nome, "pt-BR")),
];

const POR_ISO = new Map(PAISES.map((p) => [p.iso, p]));
export function paisPorIso(iso: string): Pais | undefined {
  return POR_ISO.get(iso);
}

// Bandeira emoji a partir do ISO-2 (regional indicators). Em plataformas sem
// glifo de bandeira (ex.: Windows) aparece o par de letras — ainda informativo.
export function bandeira(iso: string): string {
  if (!/^[A-Za-z]{2}$/.test(iso)) return "🏳️";
  const cc = iso.toUpperCase();
  return String.fromCodePoint(0x1f1e6 + cc.charCodeAt(0) - 65, 0x1f1e6 + cc.charCodeAt(1) - 65);
}

// Divide um número completo (dígitos) em país + local pelo MAIOR DDI que prefixa.
// Sem match → assume Brasil (default) e trata tudo como local.
export function separarDDI(fullDigits: string | null | undefined): { pais: Pais; local: string } {
  const d = String(fullDigits || "").replace(/\D/g, "");
  let melhor: Pais | null = null;
  for (const p of PAISES) {
    if (d.startsWith(p.ddi) && (!melhor || p.ddi.length > melhor.ddi.length)) melhor = p;
  }
  const brasil = POR_ISO.get("BR")!;
  if (!melhor) return { pais: brasil, local: d };
  return { pais: melhor, local: d.slice(melhor.ddi.length) };
}
